services:
  service-rs:
    build:
      context: ./service-rs
      dockerfile: Dockerfile
    ports:
      - "8199:3001"
    depends_on:
      - service-go
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      retries: 3
      start_period: 30s
      timeout: 10s
  service-go:
    build:
      context: ./service-go
      dockerfile: Dockerfile
    expose:
      - "3000"
