services:
  service-rs:
    build:
      context: ./service-rs
      dockerfile: Dockerfile
    ports:
      - "8199:3001"
    depends_on:
      - service-go
  service-go:
    build:
      context: ./service-go
      dockerfile: Dockerfile
