services:
  service-go:
    build:
      context: ./service-go
      dockerfile: Dockerfile

  service-rs:
    build:
      context: ./service-rs
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - service-go

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8198:80"
    depends_on:
      - service-rs
