cont-build:
    podman build -t service-rs -f Dockerfile

cont-run:
    podman run -dit service-rs

cont-exec: cont-build
    #!/usr/bin/env bash
    set -euxo pipefail
    hash=$(podman run -dit service-rs)
    podman exec -w=/app/ -it $hash /bin/bash

# Check all variants
check:
    cargo check
    cargo check -Fsim-delay
